version: '2'
services:
  blogapp:
    container_name: blogapp
    build: 
      context: ./modules/blogapp
      dockerfile: ./Dockerfile
    volumes:
      - ./modules/blogapp:/srv/blogapp
    ports:
      - 8088:8000
      - 8099:8000

